build:
  python_packages:
    - crewai==0.80.0
    - crewai-tools==0.14.0
    - llama-index==0.12.5
    - llama-index-tools-yahoo-finance==0.3.0
    - llama-index-llms-huggingface==0.4.1
    - yfinance==0.2.49